/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProjectsImport } from './routes/projects'
import { Route as IndexImport } from './routes/index'
import { Route as ProjectsIndexImport } from './routes/projects.index'
import { Route as ProjectsSettingsImport } from './routes/projects.settings'
import { Route as ProjectsKanbanImport } from './routes/projects.kanban'

// Create/Update Routes

const ProjectsRoute = ProjectsImport.update({
  path: '/projects',
  getParentRoute: () => rootRoute
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute
} as any)

const ProjectsIndexRoute = ProjectsIndexImport.update({
  path: '/',
  getParentRoute: () => ProjectsRoute
} as any)

const ProjectsSettingsRoute = ProjectsSettingsImport.update({
  path: '/settings',
  getParentRoute: () => ProjectsRoute
} as any)

const ProjectsKanbanRoute = ProjectsKanbanImport.update({
  path: '/kanban',
  getParentRoute: () => ProjectsRoute
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/projects': {
      preLoaderRoute: typeof ProjectsImport
      parentRoute: typeof rootRoute
    }
    '/projects/kanban': {
      preLoaderRoute: typeof ProjectsKanbanImport
      parentRoute: typeof ProjectsImport
    }
    '/projects/settings': {
      preLoaderRoute: typeof ProjectsSettingsImport
      parentRoute: typeof ProjectsImport
    }
    '/projects/': {
      preLoaderRoute: typeof ProjectsIndexImport
      parentRoute: typeof ProjectsImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  ProjectsRoute.addChildren([ProjectsKanbanRoute, ProjectsSettingsRoute, ProjectsIndexRoute])
])

/* prettier-ignore-end */
